#!/bin/bash

export ZMICRO_DATA_PARENT="${ZMICRO_DATA_PARENT}"
if [ "$(uname -s)" = "Darwin" ]; then
  export ZMICRO_DATA_PARENT=/opt
fi

export PLUGIN_JVM_DATA=${ZMICRO_DATA_PARENT}/data/plugins/jvm
export PLUGIN_JVM_VERSIONS=${PLUGIN_JVM_DATA}/versions
export PLUGIN_JVM_VERSION_CURRENT=${PLUGIN_JVM_DATA}/current

export PLUGIN_JVM_SOURCE_VERSION=""
if [ -f "$PWD/.jvmrc" ]; then
  PLUGIN_JVM_SOURCE_VERSION="$(cat $PWD/.jvmrc)"
else
  if [ -f "$PLUGIN_JVM_VERSION_CURRENT" ]; then
    PLUGIN_JVM_SOURCE_VERSION="$(cat $PLUGIN_JVM_VERSION_CURRENT)"
  fi
fi

# jvm
if [ -z "$PLUGIN_JVM_SOURCE_VERSION" ]; then
  export PLUGIN_JVM_JAVA_DEFAULT_VERSION=${PLUGIN_JVM_JAVA_DEFAULT_VERSION:-"zulu@1.11.0"}
  export PLUGIN_JVM_SOURCE_VERSION=$PLUGIN_JVM_JAVA_DEFAULT_VERSION
fi
if [ ! -d "$PLUGIN_JVM_VERSIONS/$PLUGIN_JVM_SOURCE_VERSION" ]; then
  if [ -d "$PLUGIN_JVM_VERSIONS" ]; then
    if [ -n "$(ls $PLUGIN_JVM_VERSIONS)" ]; then
      PLUGIN_JVM_SOURCE_VERSION=$(ls $PLUGIN_JVM_VERSIONS | grep $PLUGIN_JVM_SOURCE_VERSION | sort -rV | head -n 1)
    fi
  fi
fi

export PLUGIN_JVM_JAVA_CURRENT_VERSION=$PLUGIN_JVM_SOURCE_VERSION

# java
# export JAVAHOME=$PLUGIN_JVM_VERSIONS/$version
# export JAVAPATH=$HOME/.java
# export PATH=$JAVAPATH/bin:$JAVAHOME/bin:$PATH
# export JAVA_HOME=${JAVA_HOME}
[ -s "$HOME/.jabba/jabba.sh" ] && source "$HOME/.jabba/jabba.sh"

# usage:
# [ -s "$ZMICRO_HOME/plugins/jvm/source" ] && \. $ZMICRO_HOME/plugins/jvm/source
