#!/bin/bash

help() {
  echo "Usage:"
  echo "  jvm bin"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  # echo $PLUGIN_JVM_JAVA_BIN
  # which java

  [ -s "$ZMICRO_HOME/plugins/jvm/source" ] && \. $ZMICRO_HOME/plugins/jvm/source
  echo "$JAVA_HOME/bin"
}

run() {
  core $@
}

run $@
