#!/bin/bash

help() {
  echo "Set default version"
  echo ""
  echo "Usage:"
  echo "  jvm default"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local default=$(jvm::default)
  if [ -z "$default" ]; then
    echo "No version is currently set"
    exit 0
  fi

  echo "$default"
}

run() {
  core "$@"
}

run "$@"
