#!/bin/bash

jvm::current() {
  [ -s "$ZMICRO_HOME/plugins/jvm/source" ] && \. $ZMICRO_HOME/plugins/jvm/source

  echo $PLUGIN_JVM_JAVA_CURRENT_VERSION
}

# jvm::current gets the current version of Java
jvm::current_TODO() {
  if [ ! -f "${PLUGIN_JVM_VERSION_CURRENT}" ]; then
    echo ""
    return
  fi

  echo $(cat $PLUGIN_JVM_VERSION_CURRENT)
}

export -f jvm::current
