#!/bin/bash

# jvm::exec enters a new shell with go
jvm::exec() {
  local go_bin_path=$PLUGIN_JVM_JAVA_BIN
  local version=$1
  if [ -n "$version" ]; then
    version=$(vm::version_ensure_prefix_v $version)
    go_bin_path=$PLUGIN_JVM_VERSIONS/$version/bin
  fi

  which go >>/dev/null 2>&1
  if [ $? -eq 0 ]; then
    log::error "[jvm::exec] found go, you should use 'jvm use' instead of 'jvm exec'"
    return 1

    # @TODO like python virtualenv wrapper
    # local active=$PLUGIN_JVM_VERSIONS/$version/active
    # if [ ! -f $active ]; then
    #   local cleaned_path=$(echo $PATH | sed "s|$PLUGIN_JVM_JAVA_HOME||g")
    #   echo "export PATH=$go_bin_path:$cleaned_path" | sudo tee $active > /dev/null 2>&1
    # fi

    # source $active
    # exit 0
  fi

  export PATH=$go_bin_path:$PATH
  go env -w JAVA111MODULE=on
  go env -w JAVAPROXY=https://goproxy.cn,direct
  go env -w JAVAPATH=$PLUGIN_JVM_JAVA_PATH

  exec $SHELL
}

export -f jvm::exec
